// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3-0YCuOkL2a9kgS1Ayz__82gXVynL9xk',
    appId: '1:848729921293:web:4e585e64b4b72732398244',
    messagingSenderId: '848729921293',
    projectId: 'phobapp-2e31d',
    authDomain: 'phobapp-2e31d.firebaseapp.com',
    storageBucket: 'phobapp-2e31d.appspot.com',
    measurementId: 'G-DBVZXLVGF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0fydwIZ_1lQiWeR9CKGc2dcHPUELst3E',
    appId: '1:848729921293:android:03431bfc0654afa9398244',
    messagingSenderId: '848729921293',
    projectId: 'phobapp-2e31d',
    storageBucket: 'phobapp-2e31d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfu7K8dQeyKZfn-tXknVuIq4FZLaPVWVk',
    appId: '1:848729921293:ios:1125d4b5e67270f5398244',
    messagingSenderId: '848729921293',
    projectId: 'phobapp-2e31d',
    storageBucket: 'phobapp-2e31d.appspot.com',
    iosClientId: '848729921293-bqbs1shpdb7c5259b27ovmii0766mtmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.phobapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfu7K8dQeyKZfn-tXknVuIq4FZLaPVWVk',
    appId: '1:848729921293:ios:1125d4b5e67270f5398244',
    messagingSenderId: '848729921293',
    projectId: 'phobapp-2e31d',
    storageBucket: 'phobapp-2e31d.appspot.com',
    iosClientId: '848729921293-bqbs1shpdb7c5259b27ovmii0766mtmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.phobapp',
  );
}
